AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Tutorial
Parameters:
  ENVIRONMENT:
    Type: String

Resources:

  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub HelloLambda-${ENVIRONMENT}
      Handler: index.lambda_handler
      Runtime: python2.7 
      CodeUri: src 
      MemorySize: 128 
      Timeout: 20
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess  
      Events:
        MyEndpoint:
          Type: Api 
          Properties:
            Path: /test
            Method: get
      Environment:
        Variables:
          DB_TABLE_NAME: !Ref HelloTable

  HelloTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1