AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Tutorial
Parameters:
  ENVIRONMENT:
    Type: String

Resources:

  HelloAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${ENVIRONMENT}
      DefinitionBody:
        swagger: 2.0
        info:
          title:
            Ref: AWS::StackName
        paths:
          /test:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloLambda.Arn}/invocations
                responses: {}
        x-amazon-apigateway-binary-media-types:
          - '*/*'

  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub HelloLambda-${ENVIRONMENT}
      Handler: index.lambda_handler
      Runtime: python2.7 
      CodeUri: src 
      MemorySize: 128 
      Timeout: 20
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess  
      Events:
        MyEndpoint:
          Type: Api 
          Properties:
            Path: /test
            Method: get
            RestApiId:
              Ref: HelloAPI
      Environment:
        Variables:
          DB_TABLE_NAME: !Ref HelloTable

  HelloTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1